### ISSUE TITLE
请问ABCNetV2什么时候开源呢

### ISSUE THREAD

**Issue by mstd-jie** [Yuliang-Liu/ABCNet_Chinese#2]
最近一直很期待呢

**Comment by Yuliang-Liu** [comment]
@921162820 When I have 4 pieces of V100 or video cards with larger memory. Thanks for your attention.

**Comment by mstd-jie** [comment]
我有v100可以给您使用，你用不

**Comment by Yuliang-Liu** [comment]
@921162820 Thanks! My email is liu.yuliang@mail.scut.edu.cn. Do you have wechat?

**Comment by Yuliang-Liu** [comment]
@921162820  ABCNetv2 has been published in [AdelaiDet](https://github.com/aim-uofa/AdelaiDet)
