### ISSUE TITLE
ArT和synthChinese130k数据集的标注json好像不对

### ISSUE THREAD

**Issue by NO2-yh** [Yuliang-Liu/ABCNet_Chinese#4]
这两个数据集里面给的标注没有bezier points

**Comment by Yuliang-Liu** [comment]
@NO2-yh Let me check. I will update soon

**Comment by Yuliang-Liu** [comment]
@NO2-yh Already updated the download link! THX!

**Comment by ChuanyangGong** [comment]
想问一下还有 synthChinese130k 的资源吗，那个谷歌的链接下到20G就不下了
